# Generated by Django 6.0.7 on 2026-08-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Student ID / Roll Number'),
        ),
    ]
