# Generated by Django 6.0.7 on 2026-08-11 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_coursegroup_course_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
